### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by dwjsong** [jinhyung/MIPL#20]
- Singleton
  - XML Parsing
  - extends Map

**Comment by jcybha** [comment]
This is an XMLHandler example:

package org.jfm.filesystems;

import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;
import org.xml.sax.helpers.DefaultHandler;

public class FilesystemXMLHandler extends DefaultHandler {

   /_<filesystem>
    <name>TestOne</name>
    <class>jfm.org.BlaBla</class>
    <dependencies>
        <jar>jfm1.jar</jar>
        <jar>jfm2.jar</jar>
        <jar>jfm3.jar</jar>
    </dependencies>
</filesystem>_/

```
private static String FILESYSTEM_ELEMENT_NAME="filesystem";
private static String NAME_ELEMENT_NAME="name";
private static String CLASS_ELEMENT_NAME="class";
private static String DEPENDENCIES_ELEMENT_NAME="dependencies";
private static String JAR_ELEMENT_NAME="jar";

private final static int FILESYSTEM_ELEMENT=0;
private final static int NAME_ELEMENT=1;
private final static int CLASS_ELEMENT=2;
private final static int DEPENDENCIES_ELEMENT=3;
private final static int JAR_ELEMENT=4;

private int currentElement=-1;

private String name;
private String theClass;
private HashMap<String, String> hash = new HashMap<String, String>();
private java.util.List<String> dependencies=null;
```

   public void startElement (String uri, String localName,
                  String qName, Attributes attributes)
    throws SAXException
    {
        if(FILESYSTEM_ELEMENT_NAME.equals(qName)) currentElement=FILESYSTEM_ELEMENT;
        if(NAME_ELEMENT_NAME.equals(qName)) currentElement=NAME_ELEMENT;
        if(CLASS_ELEMENT_NAME.equals(qName)) currentElement=CLASS_ELEMENT;
        if(DEPENDENCIES_ELEMENT_NAME.equals(qName)) currentElement=DEPENDENCIES_ELEMENT;
        if(JAR_ELEMENT_NAME.equals(qName)) currentElement=JAR_ELEMENT;
    }

```
public void endElement (String uri, String localName, String qName)
throws SAXException
{
    currentElement=-1;
    //System.out.println("end: uri:"+uri+",localname:"+localName+" , qname:"+qName);
}

public void characters (char ch[], int start, int length)
throws SAXException
{
    switch(currentElement)
    {
        case NAME_ELEMENT:
            name=new String(ch,start,length);
            break;
        case CLASS_ELEMENT:
            theClass=new String(ch,start,length);
        hash.put(name, theClass);
            break;
        case DEPENDENCIES_ELEMENT:
            dependencies=new ArrayList<String>();
            break;
        case JAR_ELEMENT:
            dependencies.add(new String(ch,start,length));
            break;
    }
}   

public void error(SAXParseException e)
throws SAXParseException
{
    throw e;
}

/**
 * @return the dependencies
 */
public java.util.List<String> getDependencies() {
    return dependencies;
}

/**
 * @return the name
 */
public Map<String, String> getMap() {
    return hash;
}
```

}

**Comment by jcybha** [comment]
That parses: (<> ==> {})

{filesystem>
    {name>TestOne{/name}
    {class>jfm.org.BlaBla{/class}
    {dependencies>
        {jar}jfm1.jar{/jar}
        {jar}jfm2.jar{/jar]
        {jar}jfm3.jar{/jar}
    {/dependencies}
{/filesystem}

**Comment by jcybha** [comment]
This is the caller:

 private static void registerFilesystem(File f) throws ParserConfigurationException,SAXException,IOException{
      java.util.jar.JarFile jarFile=new java.util.jar.JarFile(f,false,java.util.zip.ZipFile.OPEN_READ);
      ZipEntry entry=jarFile.getEntry("filesystem.xml");
      if(entry==null)//didnt found it 
      {
          return;
      }
      //found it

```
System.out.println("found "+f+" to be a filesystem plugin");      
javax.xml.parsers.SAXParserFactory saxFactory=javax.xml.parsers.SAXParserFactory.newInstance();
SAXParser parser=saxFactory.newSAXParser();
FilesystemXMLHandler handler=new FilesystemXMLHandler();
parser.parse(jarFile.getInputStream(entry), handler);
Map<String, String> map = handler.getMap();
for(String name : map.keySet())
    registeredFilesystems.put(name, map.get(name));
```

//  String name=handler.getName();
//  String theClass=handler.getTheClass();
//  registeredFilesystems.put(name,theClass);  
    java.util.List<String> dependencies=handler.getDependencies();
    for(int i=0;i<dependencies.size();i++)
    {
        org.jfm.main.JFMClassLoader.addAditionalJar(dependencies.get(i));
    }
  }
